# Generated by Django 3.2.8 on 2022-03-19 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=200)),
                ('cor', models.CharField(max_length=15)),
                ('ano', models.IntegerField()),
                ('placa', models.CharField(max_length=15)),
                ('diaria', models.FloatField()),
                ('tipo', models.CharField(choices=[('BIS', 'BIS'), ('MOTOHONDA', 'MOTOHONDA'), ('BROSS', 'BROSS'), ('MOTOCICLETA', 'MOTOCICLETA'), ('CUPE', 'Cupe'), ('CROSSOVER', 'Crossover'), ('ESPORTIVO', 'Esportivo'), ('HATCH', 'Hacth'), ('JIPE', 'Jipe'), ('PICAPE', 'Picape'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('VAN E MINIVAM', 'Van/Minivam')], max_length=15)),
                ('status', models.CharField(choices=[('DISPONÍVEL', 'Disponível'), ('INDISPONÍVEL', 'Indisponível')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_locacao', models.DateField()),
                ('data_devolucao', models.DateField()),
                ('status', models.CharField(choices=[('EM_ABERTO', 'Em Aberto'), ('FECHADA', 'Fechada')], max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cliente')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.colaborador')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplications.veiculo')),
            ],
            options={
                'verbose_name_plural': 'Locações',
            },
        ),
    ]
