# Generated by Django 4.0.3 on 2022-03-23 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_date', models.DateField(blank=True)),
                ('return_date', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('opened', 'Em aberto'), ('closed', 'Fechado')], default='opened', max_length=9)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.client')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.vehicle')),
            ],
        ),
    ]
