# Generated by Django 4.0.3 on 2022-03-26 14:30

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_vehicle_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='return_date',
            new_name='due_date',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(upload_to=application.models.upload_image),
        ),
    ]
