# Generated by Django 4.0.3 on 2022-03-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='total',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='daily_rate',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
