# Generated by Django 4.0.3 on 2022-03-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_location_total_alter_vehicle_daily_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='daily_rate',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
