# Generated by Django 4.0.3 on 2022-03-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_location_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.vehicle'),
        ),
    ]
