# Generated by Django 4.0.3 on 2022-03-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_location_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('coupe', 'Cupê'), ('sports', 'Esportivo'), ('crossover', 'Crossover'), ('hatchback', 'Hatchback'), ('convertible', 'Conversível'), ('suv', 'SUV'), ('minivan', 'Minivan'), ('pickup', 'Picape'), ('jeep', 'Jipe')], default='', max_length=11),
        ),
    ]
